### ISSUE TITLE
Set SF2_PATH and SFZ_PATH if valid

### ISSUE THREAD

**Issue by falkTX** [flathub/studio.kx.carla#4]
Not sure if such paths exist within the freedesktop spec, but Carla supports them so we could define them.

If such paths are not defined in freedesktop, perhaps they should :)

**Comment by Bleuzen** [comment]
Setting system paths for soundfonts is not required since there are none on flathub (and most likely will never be).
User paths are also not required setting in the flatpak, since Carla ships with good defaults on its own.

Btw. the default SF2/3 paths in Carla don't look right:
![image](https://user-images.githubusercontent.com/12885163/143662615-7dac6765-cb95-47c7-9054-f449225b4e03.png)

**Comment by Bleuzen** [comment]
see https://github.com/falkTX/Carla/pull/1541
